// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Showroom.Api.Models;

namespace GenProc3D.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211031185109_InitialShowroomDB")]
    partial class InitialShowroomDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Showroom.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectThumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OwnerId = 200,
                            ProjectPath = "Projects/TestProject1",
                            ProjectThumbnail = "images / Untitled1.png",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 2,
                            OwnerId = 250,
                            ProjectPath = "Projects/TestProject2",
                            ProjectThumbnail = "images / Untitled2.png",
                            ProjectType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
